import { StyleSheet } from "react-native";

export const tyylit = StyleSheet.create({
  sailio: {
    flex: 1,
    backgroundColor: "#f4f4f4",
  },
  vieritysSisalto: {
    padding: 20,
    paddingBottom: 40,
  },
  otsikko: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 6,
    textAlign: "center",
  },
  alaotsikko: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
    color: "#555",
  },
  hakuRivi: {
    flexDirection: "row",
    marginBottom: 20,
  },
  syote: {
    flex: 1,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 48,
    marginRight: 10,
  },
  painike: {
    backgroundColor: "#222",
    paddingHorizontal: 18,
    justifyContent: "center",
    borderRadius: 8,
  },
  painikeTeksti: {
    color: "white",
    fontWeight: "600",
  },
  lataus: {
    marginVertical: 20,
  },
  virhe: {
    color: "red",
    marginBottom: 15,
    textAlign: "center",
  },
  infoTeksti: {
    textAlign: "center",
    color: "#555",
    marginTop: 10,
    marginBottom: 20,
  },
  ohjeTeksti: {
    fontSize: 13,
    color: "#666",
    marginBottom: 10,
  },
  joukkueLaatikko: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    alignItems: "center",
  },
  joukkueLogo: {
    width: 80,
    height: 80,
    resizeMode: "contain",
    marginBottom: 10,
  },
  joukkueNimi: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 8,
  },
  joukkueTieto: {
    fontSize: 15,
    marginBottom: 4,
    color: "#444",
  },
  osio: {
    marginBottom: 24,
  },
  osioOtsikko: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
  },
  kortti: {
    backgroundColor: "white",
    padding: 14,
    borderRadius: 10,
    marginBottom: 10,
  },
  otteluOtsikko: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  otteluTeksti: {
    fontSize: 14,
    color: "#444",
    marginBottom: 2,
  },
  taulukkoOtsake: {
    flexDirection: "row",
    backgroundColor: "#222",
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    marginBottom: 6,
  },
  taulukkoRivi: {
    flexDirection: "row",
    backgroundColor: "white",
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    marginBottom: 6,
    alignItems: "center",
  },
  valittuJoukkueRivi: {
    borderWidth: 2,
    borderColor: "#222",
  },
  taulukkoSijoitus: {
    width: 25,
    fontSize: 13,
    fontWeight: "700",
    color: "#333",
  },
  taulukkoJoukkue: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
  },
  taulukkoTilasto: {
    width: 28,
    fontSize: 13,
    textAlign: "center",
    color: "#333",
  },
  taulukkoPisteet: {
    width: 28,
    fontSize: 13,
    textAlign: "center",
    fontWeight: "700",
    color: "#333",
  },
  pelaajaRivi: {
    flexDirection: "row",
    backgroundColor: "white",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    alignItems: "center",
  },
  pelaajaNumero: {
    width: 28,
    fontSize: 15,
    fontWeight: "700",
    color: "#333",
  },
  pelaajaKuva: {
    width: 55,
    height: 55,
    borderRadius: 28,
    marginRight: 12,
    resizeMode: "cover",
    backgroundColor: "#ddd",
  },
  pelaajaKuvaPaikka: {
    width: 55,
    height: 55,
    borderRadius: 28,
    marginRight: 12,
    backgroundColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
  },
  pelaajaKuvaTeksti: {
    fontSize: 20,
    fontWeight: "700",
    color: "#777",
  },
  pelaajaTiedot: {
    flex: 1,
  },
  pelaajaNimi: {
    fontSize: 15,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  pelaajaTeksti: {
    fontSize: 13,
    color: "#555",
    marginBottom: 2,
  },
  profiiliKortti: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    alignItems: "center",
  },
  profiiliKuva: {
    width: 120,
    height: 120,
    borderRadius: 60,
    resizeMode: "cover",
    marginBottom: 12,
    backgroundColor: "#ddd",
  },
  profiiliKuvaPaikka: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 12,
    backgroundColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
  },
  profiiliKuvaTeksti: {
    fontSize: 36,
    fontWeight: "700",
    color: "#777",
  },
  profiiliNimi: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 10,
    textAlign: "center",
  },
  profiiliTeksti: {
    fontSize: 14,
    color: "#444",
    marginBottom: 4,
    textAlign: "center",
  },
  suljePainike: {
    backgroundColor: "#222",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 12,
  },
  suljePainikeTeksti: {
    color: "white",
    fontWeight: "700",
  },
});